---
title: "Visualizing The Most Common Words in Aimer Songs"
output:
  html_notebook:
    code_folding: hide
---

## Load Libraries
```{r}
library(dplyr)
library(ggplot2)
library(wordcloud)
library(RColorBrewer)
```

## Import and View Data
```{r}
df <- readr::read_csv("data/cleaned_data.csv")
head(df, 10)

# japanese particles that shouldn't be included in wordcloud
jpn_prtcl <- c(
               "no", "wa", "o", "mo", "ni", "e", "de", "ga",
               "to", "ya", "ne", "yo", "ka", "wo", "i", "yo",
               "kara", "yori", "na", "dake", "a", "te", "mo",
               "mou"
              )
```

## Summary Statistics
```{r}
# set ggpplot theme
theme_set(theme_light())

# top 15 songs with most words
df %>%
  group_by(Song_title) %>%
  summarise(N = sum(Count)) %>%
  arrange(desc(N)) %>%
  head(15) %>%
  ggplot(aes(x = reorder(Song_title, N), y = N)) +
  geom_bar(stat = "identity", width = 0.6) +
  coord_flip() +
  labs(
    title = "Top 15 Songs With Most Words",
    x = "Song",
    y = "Number of Words"
  )

# top 15 most used words
df %>%
  filter(!Word %in% jpn_prtcl) %>%
  group_by(Word) %>%
  summarise(N = sum(Count)) %>%
  arrange(desc(N)) %>%
  head(15) %>%
  ggplot(aes(x = reorder(Word, N), y = N)) +
  geom_bar(stat = "identity", width = 0.6) +
  coord_flip() +
  labs(
    title = "Top 15 Most Used Words",
    x = "Word",
    y = "Count"
  )

# distribution of number of words in a song
df %>%
  group_by(Song_title) %>%
  summarise(N = sum(Count)) %>%
  ggplot(aes(x = N)) +
  geom_histogram(binwidth = 15) +
  labs(
    title = "Distribution of Number of Words in a Song",
    x = "Number of Words in Song",
    y = "Count"
  )

# distribution of word counts
df %>%
  filter(!Word %in% jpn_prtcl) %>%
  group_by(Word) %>%
  summarise(N = sum(Count)) %>%
  filter(N < 200) %>%
  ggplot(aes(x = N)) +
  geom_histogram(binwidth = 2) +
  labs(
    title = "Distribution of Number of Times a Word is Used",
    x = "Number of Times a Word is Used",
    y = "Count"
  )
```

## word cloud
```{r}
# df for word cloud
newdf <- df %>%
  filter(!Word %in% jpn_prtcl) %>%
  group_by(Word) %>%
  summarise(N = sum(Count))

# for reproducibility
set.seed(2023)

# wordcloud
wordcloud(
  words = newdf$Word,
  freq = newdf$N,
  max.words = 160,
  scale = c(8, .3),
  random.order = FALSE,
  colors = brewer.pal(8, "Set2")
)
```
